# Generated by Django 5.1.4 on 2024-12-25 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(default='#', max_length=100)),
                ('employee_id', models.CharField(default='#', max_length=15)),
                ('job', models.CharField(choices=[('Choose', 'Choose'), ('Garden maintenance', 'Garden maintenance'), ('Plumbing assistance', 'Plumbing assistance'), ('Event cooking assistance', 'Event cooking assistance'), ('Carpentry', 'Carpentry'), ('Electrical work', 'Electrical work'), ('Masonry', 'Masonry'), ('Painting', 'Painting'), ('Welding assistance', 'Welding assistance'), ('Appliance servicing', 'Appliance servicing'), ('Transportation help', 'Transportation help'), ('On-call driving service', 'On-call driving service')], default='Choose', max_length=50)),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Choose', 'Choose'), ('Male', 'Male'), ('Female', 'Female')], default='Choose', max_length=10)),
                ('country_code', models.CharField(choices=[('+91', '+91')], default='+91', max_length=5)),
                ('phone', models.IntegerField()),
                ('emergency_contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address_line_1', models.CharField(default='#', max_length=100)),
                ('address_line_2', models.CharField(default='#', max_length=100)),
                ('state', models.CharField(choices=[('Choose', 'Choose'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='Choose', max_length=100)),
                ('city', models.CharField(default='#', max_length=100)),
                ('district', models.CharField(choices=[('Choose', 'Choose'), ('Kasaragod', 'Kasaragod'), ('Kannur', 'Kannur'), ('Wayanad', 'Wayanad'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Thrissur', 'Thrissur'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kottayam', 'Kottayam'), ('Alappuzha', 'Alappuzha'), ('Pathanamthitta', 'Pathanamthitta'), ('Kollam', 'Kollam'), ('Thiruvananthapuram', 'Thiruvananthapuram')], default='Choose', max_length=30)),
                ('zip_code', models.CharField(default='', max_length=6)),
                ('interview_datetime', models.DateTimeField(auto_now_add=True)),
                ('join_date', models.DateField()),
                ('min_charge', models.FloatField()),
                ('job_state', models.CharField(choices=[('Kerala', 'Kerala')], default='Kerala', max_length=10)),
                ('job_district', models.CharField(choices=[('Kasaragod', 'Kasaragod')], default='Kasaragod', max_length=20)),
                ('job_taluk', models.CharField(choices=[('Choose', 'Choose'), ('Kasaragod', 'Kasaragod'), ('Manjeshwar', 'Manjeshwar'), ('Hosdurg', 'Hosdurg'), ('Vellarikundu', 'Vellarikundu')], default='Choose', max_length=100)),
                ('job_village', models.CharField(choices=[('Choose', 'Choose'), ('Ajanur', 'Ajanur'), ('Chithari', 'Chithari'), ('Cheruvathur', 'Cheruvathur'), ('Kayyur', 'Kayyur'), ('Cheemeni', 'Cheemeni'), ('Klayikode', 'Klayikode'), ('Thimiri', 'Thimiri'), ('Madikai', 'Madikai'), ('Ambalathara', 'Ambalathara'), ('Padne', 'Padne'), ('Udinur', 'Udinur'), ('Pallikkara', 'Pallikkara'), ('Panayal', 'Panayal'), ('Pilicode', 'Pilicode'), ('Kodakkad', 'Kodakkad'), ('Maniyat', 'Maniyat'), ('Pullur', 'Pullur'), ('Periya', 'Periya'), ('North Trikaripur', 'North Trikaripur'), ('South Trikaripur', 'South Trikaripur'), ('Udma', 'Udma'), ('Bare', 'Bare'), ('Pallikkare II', 'Pallikkare II'), ('Valiyaparamba', 'Valiyaparamba'), ('Badiadka', 'Badiadka'), ('Nirchal', 'Nirchal'), ('Bela', 'Bela'), ('Munnad', 'Munnad'), ('Bedadka', 'Bedadka'), ('Kolathur', 'Kolathur'), ('Bellur', 'Bellur'), ('Nettanige', 'Nettanige'), ('Thekkil', 'Thekkil'), ('Perumbala', 'Perumbala'), ('Kaland', 'Kaland'), ('Chemnad', 'Chemnad'), ('Chengala', 'Chengala'), ('Nakraje', 'Nakraje'), ('Pady', 'Pady'), ('Muttathody', 'Muttathody'), ('Adoor', 'Adoor'), ('Delampady', 'Delampady'), ('Karadka', 'Karadka'), ('Adhur', 'Adhur'), ('Kumbadaje', 'Kumbadaje'), ('Ubrangala', 'Ubrangala'), ('Bandadka', 'Bandadka'), ('Karivedakam', 'Karivedakam'), ('Kuttikol', 'Kuttikol'), ('Madhur', 'Madhur'), ('Kudlu(Madhur)', 'Kudlu(Madhur)'), ('Shiribaglu', 'Shiribaglu'), ('Patla', 'Patla'), ('Muttathody', 'Muttathody'), ('Kudlu(Mogral Puthur)', 'Kudlu(Mogral Puthur)'), ('Puthur', 'Puthur'), ('Muliyar', 'Muliyar'), ('Padre', 'Padre'), ('Kattukukke', 'Kattukukke'), ('Enmakaje', 'Enmakaje'), ('Sheni', 'Sheni'), ('Koipady', 'Koipady'), ('Bombrana', 'Bombrana'), ('Mogral', 'Mogral'), ('Kidoor', 'Kidoor'), ('Arikady', 'Arikady'), ('Ujar Uluvar', 'Ujar Uluvar'), ('Ichilampady', 'Ichilampady'), ('Mangalpady', 'Mangalpady'), ('Uppala', 'Uppala'), ('Kodibail', 'Kodibail'), ('Mulinja', 'Mulinja'), ('Bekur', 'Bekur'), ('Kubanoor', 'Kubanoor'), ('Ichilangode', 'Ichilangode'), ('Heroor', 'Heroor'), ('Shiriya', 'Shiriya'), ('Badaje', 'Badaje'), ('Hosabettu', 'Hosabettu'), ('Kunjathur', 'Kunjathur'), ('Udyawar', 'Udyawar'), ('Kaliyoor', 'Kaliyoor'), ('Koliyoor', 'Koliyoor'), ('Thalekala', 'Thalekala'), ('Meenja', 'Meenja'), ('Kadamabar', 'Kadamabar'), ('Moodambail', 'Moodambail'), ('Majibail', 'Majibail'), ('Kuloor', 'Kuloor'), ('Paivalike', 'Paivalike'), ('Kayyar', 'Kayyar'), ('Kudalmerkala', 'Kudalmerkala'), ('Chippar', 'Chippar'), ('Bayar', 'Bayar'), ('Badoor', 'Badoor'), ('Ednad', 'Ednad'), ('Pavoor', 'Pavoor'), ('Vorkady', 'Vorkady'), ('Pathur', 'Pathur'), ('Kodlamogaru', 'Kodlamogaru'), ('Balal', 'Balal'), ('Parappa', 'Parappa'), ('Chittarikkal', 'Chittarikkal'), ('Palavayal', 'Palavayal'), ('Kallar', 'Kallar'), ('Belur', 'Belur'), ('Thayannur', 'Thayannur'), ('Kodom', 'Kodom'), ('Kinanoor', 'Kinanoor'), ('Karinthalam', 'Karinthalam'), ('Bheemanady(Kinanoor Karinthalam)', 'Bheemanady(Kinanoor Karinthalam)'), ('Cheemeni II', 'Cheemeni II'), ('Panathady', 'Panathady'), ('Bheemanady(West Eleri)', 'Bheemanady(West Eleri)'), ('West Eleri', 'West Eleri'), ('Maloth(West Eleri)', 'Maloth(West Eleri)')], default='Choose', max_length=100)),
                ('account_holder', models.CharField(default='#', max_length=100)),
                ('account_number', models.CharField(default='#', max_length=200)),
                ('bank_name', models.CharField(default='#', max_length=200)),
                ('branch', models.CharField(default='#', max_length=200)),
                ('swift_code', models.CharField(default='#', max_length=11)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
