# Generated by Django 5.1.4 on 2025-02-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeregistrationmodel',
            name='owner',
        ),
        migrations.AddField(
            model_name='employeeregistrationmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employeephotos'),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='account_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='account_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='branch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='country_code',
            field=models.CharField(blank=True, choices=[('+91', '+91')], default='+91', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='district',
            field=models.CharField(blank=True, choices=[('Choose District', 'Choose District'), ('Kasaragod', 'Kasaragod'), ('Kannur', 'Kannur'), ('Wayanad', 'Wayanad'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Thrissur', 'Thrissur'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kottayam', 'Kottayam'), ('Alappuzha', 'Alappuzha'), ('Pathanamthitta', 'Pathanamthitta'), ('Kollam', 'Kollam'), ('Thiruvananthapuram', 'Thiruvananthapuram')], default='Choose District', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='full_name',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Choose Gender', 'Choose Gender'), ('Male', 'Male'), ('Female', 'Female')], default='Choose Gender', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='job',
            field=models.CharField(blank=True, choices=[('CYJ - Choose Your Job', 'Choose Your Job'), ('APS - Appliance Servicing', 'Appliance Servicing'), ('AMS - Automobile Servicing', 'Automobile Servicing'), ('CRP - Carpentry', 'Carpentry'), ('ELW - Electrical Work', 'Electrical Work'), ('ECA - Event Cooking Assistance', 'Event Cooking Assistance'), ('GMN - Garden Maintenance', 'Garden Maintenance'), ('MSY - Masonry', 'Masonry'), ('ODS - On-call Driving Service', 'On-call Driving Service'), ('PNG - Painting', 'Painting'), ('PLA - Plumbing Assistance', 'Plumbing Assistance'), ('TRH - Transportation Help', 'Transportation Help'), ('WDA - Welding Assistance', 'Welding Assistance')], default='CYJ - Choose Your Job', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='job_district',
            field=models.CharField(blank=True, choices=[('Kasaragod', 'Kasaragod')], default='Kasaragod', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='job_state',
            field=models.CharField(blank=True, choices=[('Kerala', 'Kerala')], default='Kerala', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='job_taluk',
            field=models.CharField(blank=True, choices=[('Choose Taluk', 'Choose Taluk'), ('Kasaragod', 'Kasaragod'), ('Manjeshwar', 'Manjeshwar'), ('Hosdurg', 'Hosdurg'), ('Vellarikundu', 'Vellarikundu')], default='Choose Taluk', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='job_village',
            field=models.CharField(blank=True, choices=[('Choose Village', 'Choose Village'), ('Ajanur', 'Ajanur'), ('Chithari', 'Chithari'), ('Cheruvathur', 'Cheruvathur'), ('Kayyur', 'Kayyur'), ('Cheemeni', 'Cheemeni'), ('Klayikode', 'Klayikode'), ('Thimiri', 'Thimiri'), ('Madikai', 'Madikai'), ('Ambalathara', 'Ambalathara'), ('Padne', 'Padne'), ('Udinur', 'Udinur'), ('Pallikkara', 'Pallikkara'), ('Panayal', 'Panayal'), ('Pilicode', 'Pilicode'), ('Kodakkad', 'Kodakkad'), ('Maniyat', 'Maniyat'), ('Pullur', 'Pullur'), ('Periya', 'Periya'), ('North Trikaripur', 'North Trikaripur'), ('South Trikaripur', 'South Trikaripur'), ('Udma', 'Udma'), ('Bare', 'Bare'), ('Pallikkare II', 'Pallikkare II'), ('Valiyaparamba', 'Valiyaparamba'), ('Badiadka', 'Badiadka'), ('Nirchal', 'Nirchal'), ('Bela', 'Bela'), ('Munnad', 'Munnad'), ('Bedadka', 'Bedadka'), ('Kolathur', 'Kolathur'), ('Bellur', 'Bellur'), ('Nettanige', 'Nettanige'), ('Thekkil', 'Thekkil'), ('Perumbala', 'Perumbala'), ('Kaland', 'Kaland'), ('Chemnad', 'Chemnad'), ('Chengala', 'Chengala'), ('Nakraje', 'Nakraje'), ('Pady', 'Pady'), ('Muttathody', 'Muttathody'), ('Adoor', 'Adoor'), ('Delampady', 'Delampady'), ('Karadka', 'Karadka'), ('Adhur', 'Adhur'), ('Kumbadaje', 'Kumbadaje'), ('Ubrangala', 'Ubrangala'), ('Bandadka', 'Bandadka'), ('Karivedakam', 'Karivedakam'), ('Kuttikol', 'Kuttikol'), ('Madhur', 'Madhur'), ('Kudlu(Madhur)', 'Kudlu(Madhur)'), ('Shiribaglu', 'Shiribaglu'), ('Patla', 'Patla'), ('Muttathody', 'Muttathody'), ('Kudlu(Mogral Puthur)', 'Kudlu(Mogral Puthur)'), ('Puthur', 'Puthur'), ('Muliyar', 'Muliyar'), ('Padre', 'Padre'), ('Kattukukke', 'Kattukukke'), ('Enmakaje', 'Enmakaje'), ('Sheni', 'Sheni'), ('Koipady', 'Koipady'), ('Bombrana', 'Bombrana'), ('Mogral', 'Mogral'), ('Kidoor', 'Kidoor'), ('Arikady', 'Arikady'), ('Ujar Uluvar', 'Ujar Uluvar'), ('Ichilampady', 'Ichilampady'), ('Mangalpady', 'Mangalpady'), ('Uppala', 'Uppala'), ('Kodibail', 'Kodibail'), ('Mulinja', 'Mulinja'), ('Bekur', 'Bekur'), ('Kubanoor', 'Kubanoor'), ('Ichilangode', 'Ichilangode'), ('Heroor', 'Heroor'), ('Shiriya', 'Shiriya'), ('Badaje', 'Badaje'), ('Hosabettu', 'Hosabettu'), ('Kunjathur', 'Kunjathur'), ('Udyawar', 'Udyawar'), ('Kaliyoor', 'Kaliyoor'), ('Koliyoor', 'Koliyoor'), ('Thalekala', 'Thalekala'), ('Meenja', 'Meenja'), ('Kadamabar', 'Kadamabar'), ('Moodambail', 'Moodambail'), ('Majibail', 'Majibail'), ('Kuloor', 'Kuloor'), ('Paivalike', 'Paivalike'), ('Kayyar', 'Kayyar'), ('Kudalmerkala', 'Kudalmerkala'), ('Chippar', 'Chippar'), ('Bayar', 'Bayar'), ('Badoor', 'Badoor'), ('Ednad', 'Ednad'), ('Pavoor', 'Pavoor'), ('Vorkady', 'Vorkady'), ('Pathur', 'Pathur'), ('Kodlamogaru', 'Kodlamogaru'), ('Balal', 'Balal'), ('Parappa', 'Parappa'), ('Chittarikkal', 'Chittarikkal'), ('Palavayal', 'Palavayal'), ('Kallar', 'Kallar'), ('Belur', 'Belur'), ('Thayannur', 'Thayannur'), ('Kodom', 'Kodom'), ('Kinanoor', 'Kinanoor'), ('Karinthalam', 'Karinthalam'), ('Bheemanady(Kinanoor Karinthalam)', 'Bheemanady(Kinanoor Karinthalam)'), ('Cheemeni II', 'Cheemeni II'), ('Panathady', 'Panathady'), ('Bheemanady(West Eleri)', 'Bheemanady(West Eleri)'), ('West Eleri', 'West Eleri'), ('Maloth(West Eleri)', 'Maloth(West Eleri)')], default='Choose Village', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='min_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='state',
            field=models.CharField(blank=True, choices=[('Choose State', 'Choose State'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='Choose State', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='swift_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
