# Generated by Django 5.1.4 on 2025-02-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0003_remove_employeeregistrationmodel_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
