# Generated by Django 5.1.4 on 2025-02-01 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0004_alter_employeeregistrationmodel_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeregistrationmodel',
            name='full_name',
        ),
    ]
